# Generated by Django 4.0.6 on 2024-06-09 04:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_created_alter_comment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('robotics', 'Robotics'), ('machine learning', 'Machine Learning'), ('arduino', 'Arduino'), ('javascript', 'JavaScript'), ('web develpment', 'Web Develpment'), ('react', 'React'), ('python', 'Python'), ('other', 'Other')], max_length=78),
        ),
    ]
