# Generated by Django 4.0.6 on 2024-06-09 22:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('basic_robotics', 'Basic Robotics'), ('advanced_robotics', 'Advanced Robotics'), ('soft_robotics', 'Soft Robotics'), ('medical_robotics', 'Medical Robotics'), ('cad', 'CAD'), ('simulation', 'Simulation'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('image_processing', 'Image Processing'), ('generative_ai', 'Generative AI'), ('intelligent_system', 'Intelligent System'), ('tensorflow', 'Tensoflow'), ('pytorch', 'Pytorch')], max_length=178),
        ),
    ]
